dist: trusty
sudo: false
language: node_js
 - 6.14.0

 branches:
   only:
   -master

addons:
  code_climate:
    repo_token:  $CODE_CLIMATE
deploy:
  provider: heroku
  api_key: 0ec037c3-5356-495a-aadb-4288ba2f1169
    secure: lIpviXW+gtIoRb/0htHz4ypXKM3w1ehKmXe2WnRE9/08S1W9l9Avzr04WUJmRGhLww4NNA7yk0S+fxybRIq3GwP3hSgs7uA5CXYKVSMCvM39B9x3wH6ZlLvQq3cAxhGFfbrdSUGJHGwD/Ulyr5wXrLqNNSdL0TBKr/2lUL7LWQ+N/ofmSroEYo/jfnidwMdJW9k+3nAFk9a7qMXknFtW07AD8+okKw7JCIq3fvSwBw9qRIz30hxPNOkO6nIYL6vBFmdvzYlxfQBenchroJjiB/syeKw8i+hMvB1WY9Ogz5boktxwVi48yi6hJY4jnPmbkUO9r85gdeGY7QXtrYUjIJ0UiVdom2uWs9dhmolYtH61T8M004E0/UDcUjd4/4g4V8cwwgV/uJ0Ux15IK8g9noltMn3oMhsL3b7WPZYAJXQNXZh9so+YlYKq6QrL7mYzOrXB7r5yZjGzoAvcNfEuuNAVXFkRBu1P7mTdqZn5P8ZF5AOQvquUa2JneIvkvsbFvdrBbVLQheud7Ym01BFm9OXQYm1ZELT99pKeqCQtUYYOfH2cTjhRH/QJ+f1BexyUxE4dr9WW+Q47M9L6sDkzeP9mwD/5CWFYYI6/WybCZQDgbsraXY1SwWqPFsmdOiJCWgHiYrvtW8niQljWJbtewIuxW03XY5Suj4plHYq5MYQ=
  app: musedarts
  on:
    repo: 6-18-b/mused
