dist: trusty

sudo: false

language: node_js

node_js:
 - 6.14.0 

notifications:
  email:
    on_failure: change
    on_success: change

branches:
  only:
    - master
    - stage
    - prod

cache:
  # TODO: Use npm once functions runtime is updated to a node verion with lock files
  yarn: true
  directories:
    - node_modules # NPM packages

install:
  # TODO: Use npm again functions runtime is updated to a node verion with lock files
  - yarn install
  - yarn add firebase-ci@0.4.6 # install firebase-ci for use in creating config and deploying

script:
  
  - npm run lint
  - npm run test
  - npm run build

addons:
  code_climate:
    repo_token: $CODE_CLIMATE

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: $HEROKU_APP
